[package]
name = "ip_calculator"
version = "0.1.0"
authors = ["Léo Huteau <huteau890@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap ="*"